### ISSUE TITLE
Ask for Obama speech datasets

### ISSUE THREAD

**Issue by iamxiaoyubei** [piyushghai/SentenceGeneration#1]
@piyushghai Hi, I read "The pre-trained model is based on Obama Speech dataset" on your github description.Could you please share this database with me for my use? Thanks a lot!

**Comment by piyushghai** [comment]
@iamxiaoyubei Here you go : 
7768e495c165c2c3d6728e6e3f0ecbe6711cf3b6 

I added an executable to fetch the speech dataset

**Comment by iamxiaoyubei** [comment]
Thank you~
I thought your dataset was a speech audio dataset, but when opened it was a speech text dataset. I overlooked that it was a sentence generation project. Anyway, Thanks for your sharing~!
